default_language_version:
  python: "3.12"
default_install_hook_types: [commit-msg, pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
        args: [--unsafe]
      - id: check-merge-conflict
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.3.4
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude: >
          (?x)^(
              .*\.csv |.*\.map
          )$
  - repo: https://github.com/compilerla/conventional-pre-commit.git
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
