name: Run daily GitHub Digest

on:
  schedule:
    # Daily at 14:00 UTC (9 Central)
    - cron: "0 14 * * *"
  workflow_dispatch: {}

jobs:
  digest:
    name: GitHub Digest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install uv
        uses: yezz123/setup-uv@v4

      - name: Install Dependencies
        run: |
          uv pip install -r github-digest/requirements.txt --system

      - name: Run
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python github-digest/main.py
